// <auto-generated />
namespace DOB.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class NullableStock : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NullableStock));
        
        string IMigrationMetadata.Id
        {
            get { return "201911081506220_NullableStock"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
